branch-defaults:
  master:
    environment: compasssurferpeoples-env
  no-deploy:
    environment: null
  aws-elasticbeanstalk-env:
    environment: compasssurferpeoples-env
# global:
#   application_name: compasssurferpeoples
#   default_ec2_keyname: null
#   default_platform: Node.js
#   default_region: us-west-2
#   sc: git